<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
     <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)Templates&quot; &quot;$(TargetDir)Templates&quot; /E /Y /I" Condition="'$(IsWindows)' == 'true'" />
    <Exec Command="cp -r &quot;$(ProjectDir)Templates&quot; &quot;$(TargetDir)&quot;" Condition="'$(IsWindows)' != 'true'" />
    <Exec Command="xcopy &quot;$(ProjectDir)Include&quot; &quot;$(TargetDir)Include&quot; /E /Y /I" Condition="'$(IsWindows)' == 'true'" />
    <Exec Command="cp -r &quot;$(ProjectDir)Include&quot; &quot;$(TargetDir)&quot;" Condition="'$(IsWindows)' != 'true'" />
    <Exec Command="xcopy &quot;$(ProjectDir)Examples&quot; &quot;$(TargetDir)GroundCode&quot; /E /Y /I" Condition="'$(Configuration)' == 'Release' and '$(IsWindows)' == 'true'" />
    <Exec Command="cp -r &quot;$(ProjectDir)Examples&quot; &quot;$(TargetDir)GroundCode&quot;" Condition="'$(Configuration)' == 'Release' and '$(IsWindows)' != 'true'" />
  </Target>
  
</Project>
