
  import  gdi32, \
          gdi32_CreateCompatibleDC, 'CreateCompatibleDC', \
          gdi32_DeleteDC, 'DeleteDC', \
          gdi32_CreateCompatibleBitmap, 'CreateCompatibleBitmap', \
          gdi32_DeleteObject, 'DeleteObject', \
          gdi32_SelectObject, 'SelectObject', \
          gdi32_BitBlt, 'BitBlt', \
          gdi32_GetDIBits, 'GetDIBits', \
          gdi32_GetObject, 'GetObjectA'
