
  import  kernel32, \
          kernel32_Sleep,'Sleep', \
          kernel32_GetProcessHeap,'GetProcessHeap', \
          kernel32_HeapAlloc,'HeapAlloc', \
          kernel32_GetModuleFileNameA,'GetModuleFileNameA', \
          kernel32_HeapFree,'HeapFree', \
          kernel32_ExitProcess,'ExitProcess', \
          kernel32_WriteFile,'WriteFile', \
          kernel32_ReadFile,'ReadFile', \
          kernel32_CreateThread,'CreateThread', \
          kernel32_WaitForSingleObject,'WaitForSingleObject', \
          kernel32_WaitForSingleObjectEx,'WaitForSingleObjectEx', \
          kernel32_CloseHandle,'CloseHandle', \
          kernel32_GetExitCodeThread,'GetExitCodeThread', \
          kernel32_ExitThread,'ExitThread', \
          kernel32_GetStdHandle,'GetStdHandle',\
          kernel32_GetSystemInfo,'GetSystemInfo',\
          kernel32_GetCurrentThread,'GetCurrentThread',\
          kernel32_GetCurrentProcess,'GetCurrentProcess',\
          kernel32_GetPriorityClass,'GetPriorityClass',\
          kernel32_SetPriorityClass,'SetPriorityClass',\
          kernel32_GetThreadPriority,'GetThreadPriority',\
          kernel32_GetThreadPriorityBoost,'GetThreadPriorityBoost',\
          kernel32_GetCurrentThreadId,'GetCurrentThreadId',\
          kernel32_GetSystemPowerStatus,'GetSystemPowerStatus',\
          kernel32_GetSystemTime,'GetSystemTime',\
          kernel32_SetThreadPriority,'SetThreadPriority',\
          kernel32_GetTempPathA,'GetTempPathA',\
          kernel32_GetTickCount,'GetTickCount',\
          kernel32_GetVersion,'GetVersion',\
          kernel32_GetVersionExA,'GetVersionExA',\
          kernel32_GetThreadContext,'GetThreadContext',\
          kernel32_CreatePipe,'CreatePipe',\
          kernel32_SetHandleInformation,'SetHandleInformation',\
          kernel32_TerminateProcess,'TerminateProcess',\
          kernel32_CreateProcessA,'CreateProcessA',\
          kernel32_GetThreadLocale,'GetThreadLocale'
