
  import  kernel32, \
          kernel32_Sleep,'Sleep', \
          kernel32_GetProcessHeap,'GetProcessHeap', \
          kernel32_HeapAlloc,'HeapAlloc', \
          kernel32_GetModuleFileNameA,'GetModuleFileNameA', \
          kernel32_HeapFree,'HeapFree', \
          kernel32_ExitProcess,'ExitProcess', \
          kernel32_WriteFile,'WriteFile', \
          kernel32_ReadFile,'ReadFile', \
          kernel32_CreateThread,'CreateThread', \
          kernel32_WaitForSingleObject,'WaitForSingleObject', \
          kernel32_WaitForSingleObjectEx,'WaitForSingleObjectEx', \
          kernel32_CloseHandle,'CloseHandle', \
          kernel32_GetExitCodeThread,'GetExitCodeThread', \
          kernel32_ExitThread,'ExitThread', \
          kernel32_GetStdHandle,'GetStdHandle'
