
  import  libcurl, \
          libcurl_curl_global_init,'curl_global_init', \
          libcurl_curl_global_cleanup,'curl_global_cleanup', \
          libcurl_curl_easy_cleanup,'curl_easy_cleanup', \
          libcurl_curl_easy_init,'curl_easy_init', \
          libcurl_curl_easy_setopt,'curl_easy_setopt', \
          libcurl_curl_easy_perform,'curl_easy_perform', \
          libcurl_curl_version_info,'curl_version_info'
