
  import  mikmod, \
          mikmod_MikMod_RegisterAllDrivers,'MikMod_RegisterAllDrivers', \
          mikmod_MikMod_RegisterAllLoaders,'MikMod_RegisterAllLoaders', \
          mikmod_MikMod_Init,'MikMod_Init', \
          mikmod_Player_Load,'Player_Load', \
          mikmod_Player_Start,'Player_Start', \
          mikmod_Player_SetVolume,'Player_SetVolume', \
          mikmod_Player_Active,'Player_Active', \
          mikmod_Player_GetRow,'Player_GetRow', \
          mikmod_Player_SetPosition,'Player_SetPosition', \
          mikmod_MikMod_Update,'MikMod_Update', \
          mikmod_Player_Stop,'Player_Stop', \
          mikmod_Player_Free,'Player_Free', \
          mikmod_MikMod_Exit,'MikMod_Exit'
