
  import  msvcrt, \
          msvcrt_sprintf,'sprintf', \
          msvcrt_printf, 'printf', \
          msvcrt_fprintf,'fprintf', \
          msvcrt_fopen,  'fopen', \
          msvcrt_fclose, 'fclose', \
          msvcrt_fwrite, 'fwrite', \
          msvcrt_fflush, 'fflush', \
          msvcrt_fputs,  'fputs', \
          msvcrt_fseek,  'fseek', \
          msvcrt_fseek64,  '_fseeki64', \
          msvcrt_fread,  'fread', \
          msvcrt_fgets,  'fgets', \
          msvcrt_ftell,  'ftell', \
          msvcrt_strcmp, 'strcmp', \
          msvcrt_scanf,  'scanf', \
          msvcrt_calloc, 'calloc', \
          msvcrt_free,   'free', \
          msvcrt_sin,    'sin', \
          msvcrt_atan2,  'atan2', \
          msvcrt_cos,    'cos', \
          msvcrt_rand,   'rand', \
          msvcrt_srand,  'srand', \
          msvcrt_fabs,   'fabs', \
          msvcrt_sqrt,    'sqrt', \
          msvcrt_abs,    '_abs64', \
          msvcrt_time64, '_time64', \
          msvcrt_pow,    'pow', \
          msvcrt_strlen, 'strlen', \
          msvcrt_strstr, 'strstr', \
          msvcrt_strcpy, 'strcpy', \
          msvcrt_getch,  '_getch'
