
  import  msvcrt, \
          msvcrt_sprintf,'sprintf', \
          msvcrt_printf, 'printf', \
          msvcrt_fopen,  'fopen', \
          msvcrt_fclose, 'fclose', \
          msvcrt_fwrite, 'fwrite', \
          msvcrt_fputs,  'fputs', \
          msvcrt_fseek,  'fseek', \
          msvcrt_fread,  'fread', \
          msvcrt_fgets,  'fgets', \
          msvcrt_ftell,  'ftell', \
          msvcrt_strcmp, 'strcmp', \
          msvcrt_scanf,  'scanf', \
          msvcrt_calloc, 'calloc', \
          msvcrt_free,   'free', \
          msvcrt_sin,    'sin', \
          msvcrt_cos,    'cos', \
          msvcrt_sqrt,    'sqrt', \
          msvcrt_getch,  '_getch'
