
  import  sidelib, \
          sidelib_Test,'sidelib_Test', \
          sidelib_ConvertFonts,'sidelib_ConvertFonts', \
          sidelib_ConvertFont1024,'sidelib_ConvertFont1024', \
          sidelib_LoadImage,'sidelib_LoadImage', \
          sidelib_LoadAndExpandImage,'sidelib_LoadAndExpandImage', \
          sidelib_FlipRedAndGreenInImage, 'sidelib_FlipRedAndGreenInImage', \
          sidelib_FreeImage,'sidelib_FreeImage'
