
  import  soloud, \
          soloud_Soloud_create,'Soloud_create', \
          soloud_Soloud_init,'Soloud_init', \
          soloud_Soloud_deinit,'Soloud_deinit', \
          soloud_Soloud_destroy,'Soloud_destroy', \
          soloud_Soloud_play,'Soloud_play', \
          soloud_Soloud_setVolume,'Soloud_setVolume', \
          soloud_Soloud_setRelativePlaySpeed,'Soloud_setRelativePlaySpeed', \
          soloud_Wav_create,'Wav_create', \
          soloud_Wav_load,'Wav_load', \
          soloud_Wav_setVolume,'Wav_setVolume', \
          soloud_Wav_setLooping,'Wav_setLooping', \
          soloud_Wav_destroy,'Wav_destroy', \
          soloud_TedSid_create,'TedSid_create', \
          soloud_TedSid_load,'TedSid_load', \
          soloud_TedSid_setVolume,'TedSid_setVolume', \
          soloud_TedSid_setLooping,'TedSid_setLooping', \
          soloud_TedSid_destroy,'TedSid_destroy', \
          soloud_Speech_create,'Speech_create', \
          soloud_Speech_setText,'Speech_setText', \
          soloud_Speech_setVolume,'Speech_setVolume', \
          soloud_Speech_setLooping,'Speech_setLooping', \
          soloud_Speech_destroy,'Speech_destroy', \
          soloud_Sfxr_create,'Sfxr_create', \
          soloud_Sfxr_loadParams,'Sfxr_loadParams', \
          soloud_Sfxr_setVolume,'Sfxr_setVolume', \
          soloud_Sfxr_setLooping,'Sfxr_setLooping', \
          soloud_Sfxr_destroy,'Sfxr_destroy'
