
  import  soloud, \
          soloud_Soloud_create,'Soloud_create', \
          soloud_Soloud_init,'Soloud_init', \
          soloud_Soloud_deinit,'Soloud_deinit', \
          soloud_Soloud_destroy,'Soloud_destroy', \
          soloud_Soloud_play,'Soloud_play', \
          soloud_Soloud_setVolume,'Soloud_setVolume', \
          soloud_Soloud_setRelativePlaySpeed,'Soloud_setRelativePlaySpeed', \
          soloud_Wav_create,'Wav_create', \
          soloud_Wav_load,'Wav_load', \
          soloud_Wav_setVolume,'Wav_setVolume', \
          soloud_Wav_setLooping,'Wav_setLooping', \
          soloud_Wav_destroy,'Wav_destroy'
